story(cmd/serve): read a config file
z5labs/evrys pull request #33
Opened 2022-11-01 01:18 UTC by Zaba505

Closes #27

2022-11-02 20:10 UTC, erictg requested changes
Other than the panics, pr is fine

2022-11-02 20:10 UTC, erictg commented on cmd/cmd.go
> +			panic(err)
Should exit with a code or return an error instead of panicking.

2022-11-02 20:10 UTC, erictg commented on cmd/cmd.go
> +			panic(err)
Same issue with panic

2022-11-02 20:10 UTC, erictg commented on cmd/cmd_test.go
> +func TestLoadConfigFile(t *testing.T) {
Panic fix will affect this test

2022-11-04 01:58 UTC, Zaba505 commented on cmd/cmd.go
> +			panic(err)
[a3fc9c1](https://github.com/z5labs/evrys/pull/33/commits/a3fc9c1cb25ad35ff2ba1530681c07ccb8998834)

2022-11-04 01:58 UTC, Zaba505 commented on cmd/cmd.go
> +			panic(err)
[a3fc9c1](https://github.com/z5labs/evrys/pull/33/commits/a3fc9c1cb25ad35ff2ba1530681c07ccb8998834)

2022-11-04 01:58 UTC, Zaba505 commented on cmd/cmd.go
> +			panic(err)
[a3fc9c1](https://github.com/z5labs/evrys/pull/33/commits/a3fc9c1cb25ad35ff2ba1530681c07ccb8998834)

2022-11-04 01:58 UTC, Zaba505 commented on cmd/cmd_test.go
> +func TestLoadConfigFile(t *testing.T) {
[a3fc9c1](https://github.com/z5labs/evrys/pull/33/commits/a3fc9c1cb25ad35ff2ba1530681c07ccb8998834)

2022-11-04 15:05 UTC, erictg requested changes
Errors need to be wrapped for context of what the error is from

2022-11-04 15:05 UTC, erictg commented on cmd/cmd.go
> +					return err
error is not wrapped for context

2022-11-04 15:05 UTC, erictg commented on cmd/cmd.go
> +			return err
error is not wrapped for context

2022-11-04 15:05 UTC, erictg commented on cmd/cmd.go
> +			return err
error is not wrapped for context

2022-11-04 15:05 UTC, erictg commented on cmd/cmd.go
> +			return err
error is not wrapped for context

2022-11-05 00:58 UTC, Zaba505 commented on cmd/cmd.go
> +			return err
[456b83d](https://github.com/z5labs/evrys/pull/33/commits/456b83dd62b3f9033e24a9fe643c49b4629a5e9f)

2022-11-05 00:58 UTC, Zaba505 commented on cmd/cmd.go
> +			return err
[456b83d](https://github.com/z5labs/evrys/pull/33/commits/456b83dd62b3f9033e24a9fe643c49b4629a5e9f)

2022-11-05 00:58 UTC, Zaba505 commented on cmd/cmd.go
> +			return err
[456b83d](https://github.com/z5labs/evrys/pull/33/commits/456b83dd62b3f9033e24a9fe643c49b4629a5e9f)

2022-11-05 00:59 UTC, Zaba505 commented on cmd/cmd.go
> +					return err
[456b83d](https://github.com/z5labs/evrys/pull/33/commits/456b83dd62b3f9033e24a9fe643c49b4629a5e9f)

2022-11-05 02:23 UTC, erictg approved these changes

2022-11-05 02:25 UTC, merged