story(storage): support mongodb for recording events
z5labs/evrys pull request #52
Opened 2022-11-04 20:13 UTC by erictg

Closes #40

2022-11-05 02:04 UTC, Zaba505 requested changes

2022-11-05 02:04 UTC, Zaba505 commented on eventstore/mongo_test.go
> +func TestMongo(t *testing.T) {
Need more test cases. For example, what happens if there is no mongo instance to connect to.

2022-11-05 02:04 UTC, Zaba505 commented on eventstore/mongo_test.go
> +	req.NoError(client.Ping(ctx, readpref.Primary()), "failed to ping mongo")
Could we pull method/function calls out of `req.NoError` for better readability?

2022-11-05 02:04 UTC, Zaba505 commented on eventstore/mongo_test.go
> +	req.NoError(mongoImpl.PutEvent(ctx, &_event), "failed to put event")
Could we pull method/function calls out of req.NoError for better readability?

2022-11-05 02:04 UTC, Zaba505 commented on eventstore/mongo_test.go
> +	req.NoError(cursor.All(ctx, &results), "failed to convert to array")
Could we pull method/function calls out of req.NoError for better readability?

2022-11-05 02:04 UTC, Zaba505 commented on eventstore/mongo_test.go
> +	req.Len(results, 1, "returned slice not of correct length")
Should also validate the data stored not just its existence

2022-11-05 02:27 UTC, erictg commented on eventstore/mongo_test.go
> +func TestMongo(t *testing.T) {
check updated commit

2022-11-08 20:13 UTC, erictg commented on eventstore/mongo_test.go
> +	req.NoError(client.Ping(ctx, readpref.Primary()), "failed to ping mongo")
check updated commit

2022-11-08 20:13 UTC, erictg commented on eventstore/mongo_test.go
> +	req.NoError(mongoImpl.PutEvent(ctx, &_event), "failed to put event")
check updated commit

2022-11-08 20:13 UTC, erictg commented on eventstore/mongo_test.go
> +	req.NoError(cursor.All(ctx, &results), "failed to convert to array")
check updated commit

2022-11-08 20:13 UTC, erictg commented on eventstore/mongo_test.go
> +	req.Len(results, 1, "returned slice not of correct length")
check updated commit

2022-11-15 04:23 UTC, Zaba505 requested changes

2022-11-15 16:07 UTC, erictg commented on README.md
> +# A cloud agnostic, pluggable event store
markdown linter

2022-11-15 16:09 UTC, erictg commented on eventstore/mongo.go
> +		return nil, fmt.Errorf("failed to init, %w", err)
in this case I don't think so, `init()` is returning custom errors

2022-11-15 16:10 UTC, erictg commented on eventstore/store.go
>  type PutEvent interface {
sure

2022-11-15 20:15 UTC, erictg commented on eventstore/mongo.go
> +	_, err = coll.InsertOne(ctx, bdoc)
yeah, the argument is just the id of the record in mongo

2022-11-17 07:13 UTC, Zaba505 requested changes

2022-11-17 07:13 UTC, Zaba505 commented on README.md
> +# A cloud agnostic, pluggable event store
Can you revert it back?

2022-11-17 07:13 UTC, Zaba505 commented on eventstore/mongo.go
> +	_, err = coll.InsertOne(ctx, bdoc)
Do we want it for logging purposes?

2022-11-17 07:13 UTC, Zaba505 commented on eventstore/store.go
> +type AppendOnly interface {
Do we instead want to go with a Go std naming convetion of `Appender`?

2022-11-17 07:13 UTC, Zaba505 commented on eventstore/store.go
> +	AppendEvent(ctx context.Context, event *event.Event) error
I think the word `Event` here is redundant since both the package and second argument have the word event in their names.

2022-11-17 07:13 UTC, Zaba505 commented on eventstore/mongo.go
> +	err = client.Ping(ctx, readpref.Primary())
I meant to ask before but is the Ping necessary? I could this potentially throwing false positives in start up. For example, an intermittent network issue leads to Ping failing but if it just waited or retried then it would see that it is in fact connected. What are your thoughts?

2022-11-17 07:14 UTC, Zaba505 commented on eventstore/mongo.go
> +		return nil, errors.New("context can not be nil")
Could you please respond here and I'll then resolve this convo, https://github.com/z5labs/evrys/discussions/60

2022-11-17 07:56 UTC, erictg commented on README.md
> +# A cloud agnostic, pluggable event store
Isn't it better to use proper markdown?

2022-11-17 07:56 UTC, erictg commented on eventstore/mongo.go
> +		return nil, errors.New("context can not be nil")
I responded to the discussion

2022-11-17 07:57 UTC, erictg commented on eventstore/mongo.go
> +	_, err = coll.InsertOne(ctx, bdoc)
We're using our own Id from the event store, in practice this will never be used so idk what value would be added in logging it, however it doesn't hurt either

2022-11-17 23:12 UTC, erictg commented on eventstore/store.go
> +type AppendOnly interface {
i dont think it matters

2022-11-18 01:25 UTC, merged