story(notifications): support apache kafka
z5labs/evrys pull request #55
Opened 2022-11-06 03:44 UTC by Zaba505

Closes #24

2022-11-10 18:34 UTC, erictg requested changes
move errors into a package level error file

2022-11-10 18:34 UTC, erictg commented on notification/bus.go
> +	// Publish
more descriptive comment needed

2022-11-10 18:34 UTC, erictg commented on notification/bus.go
> +// Bus
more descriptive comment needed

2022-11-10 18:34 UTC, erictg commented on notification/bus.go
> +func (e Error) Error() string {
need comment for exported function

2022-11-10 18:34 UTC, erictg commented on notification/bus.go
> +func (e Error) Unwrap() error {
need comment for exported function

2022-11-10 18:34 UTC, erictg commented on notification/bus.go
> +func (e MarshalError) Error() string {
need comment for exported function

2022-11-10 18:34 UTC, erictg commented on notification/bus.go
> +func (e MarshalError) Unwrap() error {
need comment for exported function

2022-11-10 18:34 UTC, erictg commented on notification/bus.go
> +func (e ConfigurationError) Error() string {
need comment for exported function

2022-11-10 18:34 UTC, erictg commented on notification/bus.go
> +func (e ConfigurationError) Unwrap() error {
need comment for exported function

2022-11-10 18:34 UTC, erictg commented on notification/bus.go
> +func (e ValidationError) Error() string {
need comment for exported function

2022-11-10 18:34 UTC, erictg commented on notification/bus.go
> +func (e ValidationError) Unwrap() error {
need comment for exported function

2022-11-10 18:34 UTC, erictg commented on notification/bus.go
> +	ErrInvalidEventSource = errors.New("event source must be non-empty and non-blank")
need comments for exported types

2022-11-10 18:34 UTC, erictg commented on notification/kafka.go
> +// KafkaBus
need more descriptive comment

2022-11-10 18:34 UTC, erictg commented on notification/kafka.go
> +// KafkaConfig
need more descriptive comment

2022-11-10 18:34 UTC, erictg commented on notification/kafka.go
> +	ErrMissingKafkaAddrs = errors.New("kafka addresses are required")
need comment for exported value

2022-11-10 18:34 UTC, erictg commented on notification/kafka.go
> +		})
panic bad, return an error instead of panicking

2022-11-10 18:34 UTC, erictg commented on notification/kafka.go
> +// Publish
need more descriptive comment

2022-11-10 18:34 UTC, erictg commented on notification/kafka.go
> +	Logger                 *zap.Logger
why provide the logger via the config. Wouldn't it be better to use the global zap for consistency and just add required fields for kafka?

2022-11-10 18:34 UTC, erictg commented on notification/kafka.go
> +	AllowAutoTopicCreation bool
add validator tags and use the validator for this

2022-11-15 04:31 UTC, Zaba505 commented on notification/kafka.go
> +	Logger                 *zap.Logger
Global state should always be avoided. Only the `cmd` package is using the global logger and that's simply cuz I haven't updated it yet to not use the global one.

2023-02-10 23:42 UTC, Zaba505 commented
No longer going this route

2023-02-10 23:42 UTC, closed without merging