story(grpc): implement Append rpc
z5labs/evrys pull request #68
Opened 2023-02-12 18:26 UTC by Zaba505

Closes #32

2023-02-13 15:39 UTC, erictg requested changes
Some non test exported functions had insufficient comments. Other than that and the one comment I left, looks great!

2023-02-13 15:39 UTC, erictg commented on svc-event-log/grpc/service.go
> +
Should there be an info log stating that an event was recorded?

2023-02-14 01:32 UTC, Zaba505 commented on svc-event-log/grpc/service.go
> +
@erictg [46aa2a1](https://github.com/z5labs/evrys/pull/68/commits/46aa2a1519cadd64a68de0d29f6a5ef6710a50e2)

2023-02-14 16:04 UTC, erictg approved these changes

2023-02-14 16:06 UTC, merged